### ISSUE TITLE
c_wr register is not resetable

### ISSUE THREAD

**Issue by mo-hosni** [shalan/MS_QSPI_XIP_CACHE#2]
c_wr register is not resetable here:
https://github.com/shalan/MS_QSPI_XIP_CACHE/blob/0e9e588c82a10fbb2f46d446bf42477df35ecfaf/hdl/rtl/MS_QSPI_XIP_CACHE.v#L164

**Comment by shalan** [comment]
fixed in https://github.com/shalan/MS_QSPI_XIP_CACHE/commit/a4e1e15f872d821dd96b8172ac8a2782e8e5f9c2

**Comment by shalan** [comment]
fixed in https://github.com/shalan/MS_QSPI_XIP_CACHE/commit/a4e1e15f872d821dd96b8172ac8a2782e8e5f9c2

**Comment by shalan** [comment]
fixed in https://github.com/shalan/MS_QSPI_XIP_CACHE/commit/a4e1e15f872d821dd96b8172ac8a2782e8e5f9c2
